token:
  expiration_time: 86400000 
  secret: '{cipher}AQAa7dNnjnb09wfZOvTZewLJUGh4GmWBkwGcM7nI8EtfHjgHvshLtaO+0wVB1hpWGnb80WaFX+yFaN9kNfq+QSdBW/6Slh8xZaeIrRHUdoP7TpaWEdTTzO2PmXGTjs6AUmmdYPMO9by7oPyZzYCqiEY7Ivziz/ry1pv6Yr2aIOTpoTj4NBCDM4r0NGwrye3cctUGWcQBS5FwyyQ0b60ifVNQaKZ5QmLdkpgcloQ2vQT1puxUPjKpHaSfm+1QYMLuENIrTpnXeK9I4z+uzDozP2MDSPzvrwjHXcJ8vKQnbywVbKT5ug+sgJwge78BsBGE2+EpLt90HOkkpkkdxaMvmnOCOSzhAD6HAI/fkGARElfqmuuzwg2eGsSn+aF46eOgPRGWZPG033XiEKxf7D1a0BD1jttJABwnPC50NVHqFdWTYceZPaN8cKiNkGVl89hKW27bDWxbTvmsQuqatyP4pnvGGsTgbeba7tbVETlIYlNrJK71B2+f7G1e0g7Om+1ZSLeKWxLXpwIgLFEAbu3lDFzdVw7/wTAUvvisxWQh3aIQFbd1RpE1kVbpOfe9PW9C0lWj+Oss57SUiC8TPsXJn9BKUdjRabb1+Z9yw2eZnwBv4hwRQyaCAPDMYH8EQOg3Vnc='

gateway:
  ip: 192.168.1.28
